# Generated by Django 5.0.2 on 2024-03-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_remove_despesas_imagem_categorias_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
