# Generated by Django 5.0.2 on 2024-03-01 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesas",
            name="categorias",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="despesas.categorias"
            ),
        ),
    ]
