# Generated by Django 5.0.2 on 2024-03-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0004_alter_despesas_categorias"),
    ]

    operations = [
        migrations.RenameField(
            model_name="despesas", old_name="categorias", new_name="categoria",
        ),
    ]
