# Generated by Django 5.0.2 on 2024-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0006_despesas_imagem"),
    ]

    operations = [
        migrations.RemoveField(model_name="despesas", name="imagem",),
        migrations.AddField(
            model_name="categorias",
            name="imagem",
            field=models.ImageField(default="", upload_to="images"),
            preserve_default=False,
        ),
    ]
